[package]
name = "fd_topo"
version.workspace = true
edition.workspace = true

[features]
logging = ["dep:fd_log"]

[dependencies]
fd_topo_sys = { path = "../fd_topo_sys" }
fd_log = { path = "../../../util/log/fd_log", optional = true }
firedancer-rs-common = { path = "../../../common" }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[[example]]
name = "init_and_exec"
path = "examples/init_and_exec.rs"

[dev-dependencies]