[package]
name = "fd_zstd_sys"
version.workspace = true
edition.workspace = true
build = "build.rs"
links = "fdzstd"

[dependencies]
libc = { version = "0.2", default-features = false }

[build-dependencies]
bindgen = { version = "0.72.1" }
cc = "1.0"
firedancer-rs-common = { path = "../../../common" }

[dev-dependencies]